server:
  port: 8080

spring:
  application:
    name: RailGoServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/railgo_db
    username: root
    password: Hop2005@

  data:
    redis:
      host: localhost
      port: 6379
      password: Hop2005@
      timeout: 2000

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      default-encoding: UTF-8

  jwt:
    expiration: 3600 #hours = 1 * 60 * 60
    expiration-refresh-token: 86400 #days =  24 * 60 * 60
    secretKeyAccess: =

payment:
  VNPay:
    tmn-code:
    secret-key:
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url:
    time-out: 15

logging:
  level:
    org:
      springframework.security: DEBUG