server:
  port: 8080

spring:
  application:
    name: airlineServer
  jmx:
    enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://147.93.29.117:3308/airline_db}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Hop2005@}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #    hibernate:
  #      ddl-auto: update

  data:
    redis:
      host: ${SPRING_REDIS_HOST:147.93.29.117}
      port: ${SPRING_REDIS_PORT:6379}
      password: Hop2005@
      timeout: 2000

      key:
        flight:
          detail-session: flightId_%s_sessionId:%s
        ticket:
          ticket-confirm:
            value:  ticket_confirm:%s
            timout: 900
          ticket-payment:
            value: ticket_payment:%s

  kafka:
    bootstrap-servers: 147.93.29.117:9092,147.93.29.117:9093
    topic:
      email: email-topic
      ticket:
        ticket-cancel: ticket-cancel

  mail:
    host: smtp.gmail.com
    port: 587
    username: dqhit999@gmail.com
    password: gqua nyez oljm ygov
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      default-encoding: UTF-8

  jwt:
    expiration: 3600 #hours = 1 * 60 * 60
    expiration-refresh-token: 86400 #days =  24 * 60 * 60
    secretKeyAccess: ${SECRET_KEY_ACCESS:c29tZUNvbXBsZXhLZXlzZWN1cml0eTEyMzQ1Njc4OTA=}

payment:
  VNPay:
    tmn-code: ${VNPAY_TMN_CODE:FPBMPL8F}
    secret-key: ${VNPAY_SECRET_KEY:8YDK2KXJ6Q56KEJBOF3UBO96D8X3H134}
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://airline.dqhdev.io.vn/order/%s/status
    time-out: 1

openapi:
  service:
    api-docs: airline-server
    server: http://api.airline.dqhdev.io.vn
    title: API Service
    version: 1.0.0

api:
  prefix: api

logging:
  level:
    com:
      airline: DEBUG

    org:
      springframework.security: DEBUG