
services:
  mysql:
    image: mysql:8.0
    container_name: railgo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hop2005@
      MYSQL_DATABASE: railgo_db
      MYSQL_USER: railgo_admin
      MYSQL_PASSWORD: Hop2005@
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

