
services:
  mysql:
    image: mysql:8.0
    container_name: railgo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hop2005@
      MYSQL_DATABASE: railgo_db
      MYSQL_USER: railgo_admin
      MYSQL_PASSWORD: Hop2005@
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: railgo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  redis_data:

